name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - name: Install Node & Yarn
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Go modules
        run: go mod download
      
      - name: Build Frontend
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn --cwd frontend install
          yarn --cwd frontend build
      - name: Build Backend
        run: go build -v

      - name: Test
        run: go test ./...
