name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: "^1.25"
      - name: Install Node & Yarn
        uses: actions/setup-node@v6
        with: 
          node-version: '24'
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Download Go modules
        run: go mod download
      
      - name: Build Frontend
        run: |
          cd frontend
          corepack enable
          corepack prepare
          yarn install
          yarn build
      - name: Build Backend
        run: go build -v

      - name: Test
        run: go test ./...
